export const START_ORIENTATION_LISTENER = "START_ORIENTATION_LISTENER";
export const STOP_ORIENTATION_LISTENER = "STOP_ORIENTATION_LISTENER";
export const START_MOTION_LISTENER = "START_MOTION_LISTENER";
export const STOP_MOTION_LISTENER = "STOP_MOTION_LISTENER";
export const SET_ORIENTATION_DEVICE_MODE = "SET_ORIENTATION_DEVICE_MODE";
export const SET_ORIENTATION_REFERENCE_MODE = "SET_ORIENTATION_REFERENCE_MODE";
export const ENABLE_G_ACCELARATION = "ENABLE_G_ACCELARATION";
export const DISABLE_G_ACCELARATION = "DISABLE_G_ACCELARATION";
export const ENABLE_QUATERNIONS_COMPUTATION = "ENABLE_QUATERNIONS_COMPUTATION";
export const DISABLE_QUATERNIONS_COMPUTATION =
  "DISABLE_QUATERNIONS_COMPUTATION";
