export const SS_SERVER_CONNECT = "SS_SERVER_CONNECT";
export const SS_SERVER_RECONNECT = "SS_SERVER_RECONNECT";
export const SS_SERVER_DISCONNECT = "SS_SERVER_DISCONNECT";
export const WRTC_INIT = "WRTC_INIT";
export const WRTC_CREATE_OFFER = "WRTC_CREATE_OFFER";
