export const WRTC_IDLE = "WRTC_IDLE";

export const WRTC_INIT_START = "WRTC_INIT_START";
export const WRTC_INIT_SUCCESS = "WRTC_INIT_SUCCESS";
export const WRTC_INIT_ERROR = "WRTC_INIT_ERROR";

export const WRTC_CREATE_OFFER_START = "WRTC_CREATE_OFFER_START";
export const WRTC_CREATE_OFFER_SUCCESS = "WRTC_CREATE_OFFER_SUCCESS";
export const WRTC_CREATE_OFFER_ERROR = "WRTC_CREATE_OFFER_ERROR";
export const WRTC_OFFER_RECEIVED = "WRTC_OFFER_RECEIVED";

export const WRTC_CREATE_ANSWER_START = "WRTC_CREATE_ANSWER_START";
export const WRTC_CREATE_ANSWER_SUCCESS = "WRTC_CREATE_ANSWER_SUCCESS";
export const WRTC_CREATE_ANSWER_ERROR = "WRTC_CREATE_ANSWER_ERROR";
export const WRTC_ANSWER_RECEIVED = "WRTC_ANSWER_RECEIVED";

export const WRTC_LOCAL_ICE_CANDIDATE_SUCCESS =
  "WRTC_LOCAL_ICE_CANDIDATE_SUCCESS";
export const WRTC_LOCAL_ICE_CANDIDATE_ERROR = "WRTC_LOCAL_ICE_CANDIDATE_ERROR";

export const WRTC_REMOTE_ICE_CANDIDATE_RECEIVED =
  "WRTC_REMOTE_ICE_CANDIDATE_RECEIVED";

export const WRTC_VIDEO_INITIALIZED = "WRTC_VIDEO_INITIALIZED";
