export const PROMPT = "WS_ST_PROMPT";
export const READY = "WS_ST_READY";
export const CONNECTING = "WS_ST_CONNECTING";
export const CONNECTION_SUCCESSFUL = "WS_ST_CONNECTION_SUCCESSFUL";
export const CONNECTION_FAILED = "WS_ST_CONNECTION_FAILED";
export const DISCONNECTED = "WS_ST_DISCONNECTED";
export const ERROR = "WS_ST_ERROR";
