export const ADD_ON_PRESSED = "ADD_ON_PRESSED";
export const REMOVE_ON_PRESSED = "REMOVE_ON_PRESSED";
export const ADD_ON_RELEASED = "ADD_ON_RELEASED";
export const REMOVE_ON_RELEASED = "REMOVE_ON_RELEASED";
export const ADD_ON_DRAGGED = "ADD_ON_DRAGGED";
export const REMOVE_ON_DRAGGED = "REMOVE_ON_DRAGGED";
