export const CAM_REQUEST_PERMS = "CAM_REQUEST_PERMISSIONS";
export const CAM_GRANT_PERMS = "CAM_GRANT_PERMS";
export const CAM_DENY_PERMS = "CAM_DENY_PERMS";
export const CAM_REVOKE_PERMS = "CAM_REVOKE_PERMS";
