export const CAM_PERMS_NOT_REQUESTED = "CAM_PERMS_NOT_REQUESTED";
export const CAM_PERMS_REQUESTED = "CAM_PERMS_REQUESTED";
export const CAM_PERMS_GRANTED = "CAM_PERMS_GRANTED";
export const CAM_PERMS_DENIED = "CAM_PERMS_DENIED";
export const CAM_PERMS_REVOKED = "CAM_PERMS_REVOKED";
