export const MOSENS_PERMS_NOT_REQUESTED = "MOSENS_PERMS_NOT_REQUESTED";
export const MOSENS_PERMS_REQUESTED = "MOSENS_PERMS_REQUESTED";
export const MOSENS_PERMS_GRANTED = "MOSENS_PERMS_GRANTED";
export const MOSENS_PERMS_DENIED = "MOSENS_PERMS_DENIED";
export const MOSENS_PERMS_REVOKED = "MOSENS_PERMS_REVOKED";
