export const MOSENS_REQUEST_PERMS = "MOSENS_REQUEST_PERMS";
export const MOSENS_GRANT_PERMS = "MOSENS_GRANT_PERMS";
export const MOSENS_DENY_PERMS = "MOSENS_DENY_PERMS";
export const MOSENS_REVOKE_PERMS = "MOSENS_REVOKE_PERMS";
