export const ORSENS_REQUEST_PERMS = "MOSENS_REQUEST_PERMS";
export const ORSENS_GRANT_PERMS = "MOSENS_GRANT_PERMS";
export const ORSENS_DENY_PERMS = "MOSENS_DENY_PERMS";
export const ORSENS_REVOKE_PERMS = "MOSENS_REVOKE_PERMS";
