export const ORSENS_PERMS_NOT_REQUESTED = "ORSENS_PERMS_NOT_REQUESTED";
export const ORSENS_PERMS_REQUESTED = "ORSENS_PERMS_REQUESTED";
export const ORSENS_PERMS_GRANTED = "ORSENS_PERMS_GRANTED";
export const ORSENS_PERMS_DENIED = "ORSENS_PERMS_DENIED";
export const ORSENS_PERMS_REVOKED = "ORSENS_PERMS_REVOKED";
