//  WS Connection actions
export const INIT_WS_CONNECTION = "MIS_AC_INIT_WS_CONNECTION";
export const START_WS_CONNECTION = "MIS_AC_START_WS_CONNECTION";
export const INIT_SPAWN_SIGNAL = "MIS_ST_INIT_SPAWN_SIGNAL";
export const SEND_SPAWN_SIGNAL = "MIS_AC_SEND_SPAWN_SIGNAL";
export const SHIFT_SPAWN_SUCCESS = "MIS_AC_SHIFT_SPAWN_SUCCESS";
export const SHIFT_SPAWN_FAILED = "MIS_AC_SHIFT_SPAWN_FAILED";
export const INIT_DESPAWN_ROUTINE = "MIS_AC_INIT_DESPAWN_ROUTINE";
export const START_DESPAWN_ROUTINE = "MIS_AC_START_DESPAWN_ROUTINE";

//  IPT actions
export const PROMPT_IPT = "MIS_AC_PROMPT_IPT";
export const INIT_IPT = "MIS_AC_INIT_IPT";
export const INIT_IPT_TRACKING = "MIS_AC_INIT_IPT_TRACKING";
export const START_IPT_TRACKING = "MIS_AC_START_IPT_TRACKING";
export const INIT_IPT_STREAM = "MIS_AC_INIT_IPT_STREAM";
export const START_IPT_STREAM = "MIS_AC_START_IPT_STREAM";
export const INIT_IPT_HALT = "MIS_AC_INIT_IPT_HALT";
export const HALT_IPT_STREAM = "MIS_AC_HALT_IPT_STREAM";
