export const PROMPT = "MIS_ST_PROMPT";
export const READY = "MIS_ST_READY";

//  WS Connection states
export const CONNECTING = "MIS_ST_CONNECTING";
export const CONNECTION_SUCCESSFUL = "MIS_ST_CONNECTION_SUCCESSFUL";
export const CONNECTION_FAILED = "MIS_ST_CONNECTION_FAILED";
export const DISCONNECTED = "MIS_ST_DISCONNECTED";

//  Spawning Cycle
export const SPAWNING_GAME_INSTANCE = "MIS_ST_SPAWNING_GAME_INSTANCE";
export const SPAWN_SUCCESSFUL = "MIS_ST_SPAWN_SUCCESSFUL";
export const SPAWN_FAILED = "MIS_ST_SPAWN_FAILED";
export const DESPAWNING_GAME_INSTANCE = "MIS_ST_DESPAWNING_GAME_INSTANCE";
export const DESPAWN_SUCCESSFUL = "MIS_ST_DESPAWN_SUCCESSFUL";
export const DESPAWN_FAILED = "MIS_ST_DESPAWN_FAILED";

//  IPT states
export const IPT_PROMPT = "IPT_PROMPT";
export const IPT_READY = "IPT_READY";
export const IPT_INIT_TRACKING = "IPT_INIT_TRACKING";
export const IPT_TRACKING = "IPT_TRACKING";
export const IPT_STREAMING_DATA = "IPT_STREAMING_DATA";
export const IPT_INIT_HALTING = "IPT_INIT_HALTING";
export const IPT_HALTED = "IPT_HALTED";
