export const INIT_MBS_CONNECTION = "GPUI_AC_INIT_MBS_CONNECTION";
export const INIT_MIS_CONNECTION = "GPUI_AC_INIT_MIS_CONNECTION";
export const RESTART_MBS_CONNECTION = "GPUI_AC_RESTART_MBS_CONNECTION";
export const RESTART_MIS_CONNECTION = "GPUI_AC_RESTART_MIS_CONNECTION";
export const KILL_MBS_CONNECTION = "GPUI_AC_KILL_MBS_CONNECTION";
export const KILL_MIS_CONNECTION = "GPUI_AC_KILL_MIS_CONNECTION";
export const REQUEST_SPAWN_INSTANCE = "GPUI_AC_REQUEST_SPAWN_INSTANCE";
export const REQUEST_DESPAWN = "GPUI_AC_REQUEST_DESPAWN";
