export const GPUI_ST_PROMPT = "GPUI_ST_PROMPT";
export const GPUI_ST_CONNECTING = "GPUI_ST_CONNECTING";
export const GPUI_ST_PAIRING = "GPUI_ST_WEBRTC_PAIRING";
export const GPUI_ST_VIDEO_LOADING = "GPUI_ST_VIDEO_LOADING";
export const GPUI_ST_VIDEO_READY = "GPUI_ST_VIDEO_READY";
export const GPUI_ST_ENDED = "GPUI_ST_ENDED";
export const GPUI_ST_ERROR = "GPUI_ST_ERROR";
