// MBS
export const MBS_PROMPT = "GPUI_ST_MBS_PROMPT";
export const MBS_READY = "GPUI_ST_MBS_READY";
export const MBS_INITIALIZING = "GPUI_ST_MBS_INITIALIZING";
export const MBS_PAIRING = "GPUI_ST_MBS_PAIRING";
export const MBS_LOADING_STREAM = "GPUI_ST_MBS_LOADING_STREAM";
export const MBS_STREAM_LOADED = "GPUI_ST_MBS_STREAM_LOADED";

//  MIS
export const MIS_PROMPT = "GPUI_ST_MIS_PROMPT";
export const MIS_READY = "GPUI_ST_MIS_READY";
export const MIS_CONNECTED = "GPUI_ST_MIS_CONNECTED";
export const MIS_REQUESTING_SPAWN = "GPUI_ST_MIS_REQUESTING_SPAWN";
export const MIS_SPAWN_REQUEST_SUCCESSFUL =
  "GPUI_ST_MIS_SPAWN_REQUEST_SUCCESSFUL";
export const MIS_DESPAWNING = "GPUI_ST_MIS_DESPAWNING";
export const MIS_TERMINATED = "GPUI_ST_MIS_TERMINATED";
