export const DM_STATE_STANDBY = "DM_STATE_STANDBY";
export const DM_STATE_RUNNING = "DM_STATE_RUNNING";
export const DM_STATE_STOPPED = "DM_STATE_STOPPED";
export const DM_STATE_ERROR = "DM_STATE_ERROR";
