export const MBS_AC_START_SS_CONNECTION = "MBS_AC_START_SS_CONNECTION";
export const MBS_AC_START_PAIRING = "MBS_AC_START_PAIRING";
export const MBS_AC_CREATE_OFFER = "MBS_AC_CREATE_OFFER";
export const MBS_AC_KILL_SS_CONNECTION = "MBS_AC_START_SS_CONNECTION";
export const MBS_AC_KILL_SS_PAIRING = "MBS_AC_KILL_SS_PAIRING";
