export const MBS_ST_PROMPT = "MBS_ST_PROMPT";
export const MBS_ST_READY = "MBS_ST_READY";

//  Signaling Service Connection
export const MBS_ST_SS_CONNECTING = "MBS_ST_CONNECTING";
export const MBS_ST_SS_CONNECTION_SUCCESSFUL = "MBS_ST_CONNECTION_SUCCESSFUL";
export const MBS_ST_SS_CONNECTION_FAILED = "MBS_ST_CONNECTION_FAILED";

//  WebRTC Initializing
export const MBS_ST_WRTC_INIT_SUCCESSFUL = "MBS_ST_WRTC_INIT_SUCCESSFUL";

//  WebRTC Handshake
export const MBS_ST_WRTC_PAIRING = "MBS_ST_WRTC_PAIRING";
export const MBS_ST_WRTC_PAIRING_SUCCESSFUL = "MBS_ST_WRTC_PAIRING_SUCCESSFUL";
export const MBS_ST_WRTC_PAIRING_FAILED = "MBS_ST_WRTC_PAIRING_FAILED";

//  WebRTC Video Feed
export const MBS_ST_WRTC_VIDEO_INITIALIZED = "MBS_ST_WRTC_VIDEO_INITIALIZED";
export const MBS_ST_VIDEO_PLAYING = "MBS_ST_VIDEO_PLAYING";
export const MBS_ST_VIDEO_PAUSED = "MBS_ST_VIDEO_PAUSED";
export const MBS_ST_VIDEO_STOPPED = "MBS_ST_VIDEO_STOPPED";
export const MBS_ST_VIDEO_ERROR = "MBS_ST_VIDEO_ERROR";
